server:
  port: 50002

spring:
  application:
    name: event-eb-service
  event-bus:
    server-ip: 10.177.28.221
    producer-port: 31236
    consumer-port: 31234
    source-topic: table_quality_result
    target-topic: table_quality_result
    consumer-group: g_table_quality_result
    send-times: 1
    columns: long,string,string
    # 证书信息
  credential:
    key: bigdata#system
    signature: aaayzaV5wVm2vyAlrRddubH8TRpymCLm96lhxUjWnit/YL/HupMMvouY8l3IwV9ZbyVZRnaACm/ecqL+LnM7fBVZGMLjPhXonmAZs1EcuHsK68Z/c9zF50Mdje/3hbZ+WH7qIKzYiPzDPjJFpvz1pXB+kupvicWBglzMMXQVypcNrU=
    expiredDate: 2020-08-28 19:00:00.000
    appId: bigdata_dsep



springfox:
  documentation:
    header: 消息测试服务
    swagger:
      v2:
        path: /api-docs

logging:
  level:
    root: info