server:
  port: 50002

spring:
  application:
    name: event-eb-service
  event-bus:
    server-ip: 172.30.13.177
    producer-port: 32236
    consumer-port: 32234
    source-topic: a52b4029d0f24c909b019c39e96df9d5
    target-topic: a52b4029d0f24c909b019c39e96df9d5
    consumer-group: g_a52b4029d0f24c909b019c39e96df9d5
    send-times: 10000
    columns: long,string,string
    # 证书信息
  credential:
    key: bigdata#system
    signature: aaayzaV5wVm2vyAlrRddubH8TRpymCLm96lhxUjWnit/YL/HupMMvouY8l3IwV9ZbyVZRnaACm/ecqL+LnM7fBVZGMLjPhXonmAZs1EcuHsK68Z/c9zF50Mdje/3hbZ+WH7qIKzYiPzDPjJFpvz1pXB+kupvicWBglzMMXQVypcNrU=
    expiredDate: 2020-08-28 19:00:00.000
    appId: bigdata_dsep



springfox:
  documentation:
    header: 消息测试服务
    swagger:
      v2:
        path: /api-docs

logging:
  level:
    root: info