server:
  port: 50002

spring:
  application:
    name: event-eb-service
  event-bus:
    server-ip: 172.30.13.177
    producer-port: 32236
    consumer-port: 32234
    source-topic: a52b4029d0f24c909b019c39e96df9d5
    target-topic: a52b4029d0f24c909b019c39e96df9d5
    consumer-group: g_a52b4029d0f24c909b019c39e96df9d5
    send-times: 10000
    columns: long,string,string
    # 证书信息
  credential:
    key: bigdata#system
    signature: svZegQZ8eiTeQOe+r33cGiW2IFX8uNhD7AZT3JYYbQQjTrTtvGpHJHfdBKY3FzUHnrm1jGSzv/YquxEtspCaHWl8dblQ9epKqFQwEBKuOHXfH45YtYadNzpZcKM8D/rSI745s/8R0zcwaqq3PJdk03wen0gC8GlQBbvWZ93a4Aw=
    expiredDate: 2043-06-23 00:00:00.000
    appId: bigdata_dsep



springfox:
  documentation:
    header: 消息测试服务
    swagger:
      v2:
        path: /api-docs

logging:
  level:
    root: info